### ISSUE TITLE
Photo feature Issue

### ISSUE THREAD

**Issue by selenegough** [NERC-CEH/st-helena-app#2]
Issue Description:
There is a noticeable decrease in image quality when trying to capture a picture using the Photo feature in the app and, quite often hard to focus species using the camera. When trying to capture the Deroceras reticulatum species my camera wouldn’t go into focus of the slug, which isn't a problem when using the devices default camera app.

1.	Open app
2.	Select Photo option
3.	Camera screen appears
4.	Tried to focus species is frame
5.	Image is out of focus (despite manoeuvring a trying to zoom in and out etc.) and, appears to be of lower image quality compared to images take with default camera 

Expected behaviour:
1.	Open app
2.	Select Photo option
3.	Camera screen appears
4.	Ability to tap object in camera to enable focus of camera
5.	Image is taken with species in focus and in regular quality of images taken with my phone 

Screenshots:
![IMG_0840](https://user-images.githubusercontent.com/94616675/220330944-45eca170-f079-4fe1-8cd1-658c6842b48e.PNG)
![IMG_0841](https://user-images.githubusercontent.com/94616675/220330978-3f21be93-e871-479a-9c82-6e6e146c1ffd.PNG)

Device information:
My phone:
iPhone 13, iOS 16.1.1
App version: v6.0.3 (18)

Rebecca Cairns-Wicks (Who also experienced the same issue):
Oppo find x5, Android Version 13
App version: v6.0.3 (18)

Additional context:
Image quality when taking a photo with my camera:
![image](https://user-images.githubusercontent.com/94616675/220331229-140f73f5-3315-4e03-a16e-913fc3ecd1f9.png)

**Comment by kazlauskis** [comment]
Thanks, the photos from the app will have a smaller resolution than those taken directly with the camera app. The app crops the image to a square when using the in-app camera option, and then, on upload, the website further resizes the image to a maximum of around 1000px width/height. This limitation is on the current iRecord website and the app too. Do you see further quality degradation in the St Helena app?

**Comment by selenegough** [comment]
Hi @kazlauskis thanks for the explanation, we accept the limitation. Rebecca and I haven't tried the iRecord app to compare photo quality.
However, we had the idea that when the resolution is too low for smaller species, we could advise that recorders try capturing photos with their default camera and then uploading to provide the best possible change for identification.

**Comment by kazlauskis** [comment]
I gave it another test to see if the St Helena website does something different than the iRecord site. Still, the uploaded photo quality is the same whether you add a photo through an app or directly through the website. So I wonder if suggesting users to use a default camera will make much of a difference.

I have created this test record which you can delete. It has three photos attached, one is a cropped image added through the app, another is a gallery selected (uncropped and using default camera) image added through the app and the third highest quality image (default camera and full resolution >8Mb) I have added directly through the website. In the end, all three photos have a similar resolution and quality. The reason is that Indicia database resizes all the images. You can use this link to view the images I have attached to the record, it's somewhere in the list:

https://irecordsthelena.edu.sh/explore/all?filter-taxon_meaning_list=253252


![Screenshot 2023-03-01 at 09 59 43](https://user-images.githubusercontent.com/7383162/222079006-892690ad-4e1e-412e-921b-347fad878718.png)

**Comment by selenegough** [comment]
Okay noted, thank you for the explanation will share this with any users who ask about this question.
Will go ahead a close this now.
