### ISSUE TITLE
Location not loading on Samsung Galaxy S8 with Android 9

### ISSUE THREAD

**Issue by selenegough** [NERC-CEH/st-helena-app#4]
I have a Samsung Galaxy S8 with Android 9. I try uploading a species record and pick up location. I go to the location selector and click on the button with the four directions on it. Location won't load even if I'm connected to the internet. Unsure if this is an issue with my phone, with internet speed or with the app.

This post was made by Tsvetoslav Georgiev

**Comment by kazlauskis** [comment]
Hi, there could be a few reasons the location isn't automatically picked up. Typically, an Internet connection isn't required for the GPS to work but the user must have accepted the permissions for the app to access the location services (see the pic). Can the user provide some more details about this issue? Any of this information would be very useful:

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem. Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Smartphone (please complete the following information):**
 - Device: [e.g. Motorola g7, iPhone 5 SE]
 - OS: [e.g. Android 7, iOS 11]
 - App Version [e.g. 1.0.0]. You can find this information by going to the menu tab in the app and scrolling to the bottom of the page.

**Additional context**
Add any other context about the problem here.

![IMG_3782](https://user-images.githubusercontent.com/7383162/221844011-be4bcca0-6aac-4490-8c67-16534ac515f3.JPG)

**Comment by selenegough** [comment]
Hi, 
Tsvetoslav will respond with additional details soon from his own profile.
Thanks

**Comment by TsvetoslavGeorgiev** [comment]
Hi,

I am happy to confirm that patience seems to solve the problem, it just takes a while longer for GPS location to be acquired in some areas with worse reception. All good for now.

Best,
Tsvet

**Comment by kazlauskis** [comment]
Great, thanks for the update.
